# This is a config for E2B sandbox template.
# You can use template ID (y3dioxmwncyjfc6uwyf5) or template name (vibe-nextjs-test11) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test11") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test11") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test11')

team_id = "9bcc70f7-6565-4167-9a25-5bb4a13bb99f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test11"
template_id = "y3dioxmwncyjfc6uwyf5"
